# logback config file
logging:
  config: classpath:logback-spring.xml

spring:
  servlet:
    multipart:
      # 最大支持文件大小
      max-request-size: 100MB
      # 最大支持请求大小
      max-file-size: 100MB

# 上传文件路径
file:
  upload:
    path: ./upload