spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  redis:
    database: 0
    timeout: 1000
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
#    cluster:
#      nodes: 127.0.0.1:6379
#      lettuce:
#        pool:
#          max-active: 20
#          max-wait: -1
#          max-idle: 10
#          min-idle: 0

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity

file.upload.path: ./upload