spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: info
  file:
    path: logs
    name: ${logging.file.path}/app.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
