server:
  port: 8080

spring:
  thymeleaf:
    cache: true
    encoding: UTF-8
    prefix: classpath:/template/
    suffix: .html

logging:
  level:
    root: info
  file:
    path: log
    name: ${logging.file.path}/app.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7