spring:
  profiles:
    active: ${RUN_ENV:dev}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: test_
  configuration-properties:
    prefix: text_