spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-wait: 1
        max-idle: 10
        min-idle: 0