spring:
  redis:
    cluster:
      nodes: 127.0.0.1:3001,127.0.0.1:3002,127.0.0.1:3003
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-wait: 1
        max-idle: 10
        min-idle: 0